export interface CityInfo {
  name: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
  costIndex: number;
  popularity: number;
  highlights: string[];
}

export const WORLD_CITIES: CityInfo[] = [
  { name: "Tokyo", country: "Japan", region: "Asia", lat: 35.6762, lng: 139.6503, costIndex: 4, popularity: 5, highlights: ["Shibuya", "Sushi", "Temples"] },
  { name: "Paris", country: "France", region: "Europe", lat: 48.8566, lng: 2.3522, costIndex: 4, popularity: 5, highlights: ["Eiffel Tower", "Louvre"] },
  { name: "New York", country: "USA", region: "Americas", lat: 40.7128, lng: -74.0060, costIndex: 5, popularity: 5, highlights: ["Times Square", "Central Park"] },
  { name: "London", country: "UK", region: "Europe", lat: 51.5074, lng: -0.1278, costIndex: 5, popularity: 5, highlights: ["Big Ben", "London Eye"] },
  { name: "Dubai", country: "UAE", region: "Middle East", lat: 25.2048, lng: 55.2708, costIndex: 5, popularity: 5, highlights: ["Burj Khalifa", "Desert Safari"] },
  { name: "Singapore", country: "Singapore", region: "Asia", lat: 1.3521, lng: 103.8198, costIndex: 4, popularity: 5, highlights: ["Gardens by the Bay", "Marina Bay"] },
  { name: "Bangkok", country: "Thailand", region: "Asia", lat: 13.7563, lng: 100.5018, costIndex: 2, popularity: 5, highlights: ["Grand Palace", "Street Food"] },
  { name: "Rome", country: "Italy", region: "Europe", lat: 41.9028, lng: 12.4964, costIndex: 3, popularity: 5, highlights: ["Colosseum", "Vatican City"] },
  { name: "Istanbul", country: "Turkey", region: "Europe/Asia", lat: 41.0082, lng: 28.9784, costIndex: 2, popularity: 5, highlights: ["Blue Mosque", "Grand Bazaar"] },
  { name: "Seoul", country: "South Korea", region: "Asia", lat: 37.5665, lng: 126.9780, costIndex: 3, popularity: 5, highlights: ["Gyeongbokgung", "Myeongdong"] },
  { name: "Barcelona", country: "Spain", region: "Europe", lat: 41.3851, lng: 2.1734, costIndex: 3, popularity: 5, highlights: ["Sagrada Familia", "Las Ramblas"] },
  { name: "Sydney", country: "Australia", region: "Oceania", lat: -33.8688, lng: 151.2093, costIndex: 4, popularity: 5, highlights: ["Opera House", "Bondi Beach"] },
  { name: "Amsterdam", country: "Netherlands", region: "Europe", lat: 52.3676, lng: 4.9041, costIndex: 4, popularity: 5, highlights: ["Canals", "Rijksmuseum"] },
  { name: "Berlin", country: "Germany", region: "Europe", lat: 52.5200, lng: 13.4050, costIndex: 3, popularity: 5, highlights: ["Brandenburg Gate", "Berlin Wall"] },
  { name: "Cairo", country: "Egypt", region: "Africa", lat: 30.0444, lng: 31.2357, costIndex: 1, popularity: 5, highlights: ["Pyramids", "Nile River"] },
  { name: "Rio de Janeiro", country: "Brazil", region: "Americas", lat: -22.9068, lng: -43.1729, costIndex: 2, popularity: 4, highlights: ["Christ the Redeemer", "Copacabana"] },
  { name: "Cape Town", country: "South Africa", region: "Africa", lat: -33.9249, lng: 18.4241, costIndex: 3, popularity: 4, highlights: ["Table Mountain", "Wine Lands"] },
  { name: "Mumbai", country: "India", region: "Asia", lat: 19.0760, lng: 72.8777, costIndex: 3, popularity: 5, highlights: ["Gateway of India", "Marine Drive"] },
  { name: "Delhi", country: "India", region: "Asia", lat: 28.6139, lng: 77.2090, costIndex: 2, popularity: 5, highlights: ["Red Fort", "India Gate"] },
  { name: "Bangalore", country: "India", region: "Asia", lat: 12.9716, lng: 77.5946, costIndex: 3, popularity: 4, highlights: ["Lalbagh", "Bangalore Palace"] },
  { name: "Chennai", country: "India", region: "Asia", lat: 13.0827, lng: 80.2707, costIndex: 2, popularity: 4, highlights: ["Marina Beach", "Kapaleeshwarar Temple"] },
  { name: "Kolkata", country: "India", region: "Asia", lat: 22.5726, lng: 88.3639, costIndex: 1, popularity: 4, highlights: ["Victoria Memorial", "Howrah Bridge"] },
  { name: "Hyderabad", country: "India", region: "Asia", lat: 17.3850, lng: 78.4867, costIndex: 2, popularity: 4, highlights: ["Charminar", "Golconda Fort"] },
  { name: "Ahmedabad", country: "India", region: "Asia", lat: 23.0225, lng: 72.5714, costIndex: 1, popularity: 3, highlights: ["Sabarmati Ashram", "Adalaj Stepwell"] },
  { name: "Pune", country: "India", region: "Asia", lat: 18.5204, lng: 73.8567, costIndex: 2, popularity: 3, highlights: ["Shaniwar Wada", "Aga Khan Palace"] },
  { name: "Jaipur", country: "India", region: "Asia", lat: 26.9124, lng: 75.7873, costIndex: 2, popularity: 5, highlights: ["Hawa Mahal", "Amer Fort"] },
  { name: "Agra", country: "India", region: "Asia", lat: 27.1767, lng: 78.0081, costIndex: 2, popularity: 5, highlights: ["Taj Mahal", "Agra Fort"] },
  { name: "Varanasi", country: "India", region: "Asia", lat: 25.3176, lng: 82.9739, costIndex: 1, popularity: 4, highlights: ["Ganges River", "Kashi Vishwanath"] },
  { name: "Amritsar", country: "India", region: "Asia", lat: 31.6340, lng: 74.8723, costIndex: 1, popularity: 4, highlights: ["Golden Temple", "Wagah Border"] },
  { name: "Lucknow", country: "India", region: "Asia", lat: 26.8467, lng: 80.9462, costIndex: 1, popularity: 3, highlights: ["Bara Imambara", "Chota Imambara"] },
  { name: "Surat", country: "India", region: "Asia", lat: 21.1702, lng: 72.8311, costIndex: 2, popularity: 2, highlights: ["Dumas Beach", "Diamond Market"] },
  { name: "Srinagar", country: "India", region: "Asia", lat: 34.0837, lng: 74.7973, costIndex: 2, popularity: 4, highlights: ["Dal Lake", "Shalimar Bagh"] },
  { name: "Shimla", country: "India", region: "Asia", lat: 31.1048, lng: 77.1734, costIndex: 2, popularity: 4, highlights: ["The Ridge", "Mall Road"] },
  { name: "Manali", country: "India", region: "Asia", lat: 32.2396, lng: 77.1887, costIndex: 2, popularity: 4, highlights: ["Rohtang Pass", "Hadimba Temple"] },
  { name: "Udaipur", country: "India", region: "Asia", lat: 24.5854, lng: 73.7125, costIndex: 2, popularity: 4, highlights: ["Lake Pichola", "City Palace"] },
  { name: "Jodhpur", country: "India", region: "Asia", lat: 26.2389, lng: 73.0243, costIndex: 2, popularity: 4, highlights: ["Mehrangarh Fort", "Blue City"] },
  { name: "Kochi", country: "India", region: "Asia", lat: 9.9312, lng: 76.2673, costIndex: 2, popularity: 4, highlights: ["Fort Kochi", "Chinese Fishing Nets"] },
  { name: "Goa", country: "India", region: "Asia", lat: 15.2993, lng: 74.1240, costIndex: 3, popularity: 5, highlights: ["Baga Beach", "Old Goa"] },
  { name: "Dehradun", country: "India", region: "Asia", lat: 30.3165, lng: 78.0322, costIndex: 2, popularity: 3, highlights: ["Robber's Cave", "Sahastradhara"] },
  { name: "Chandigarh", country: "India", region: "Asia", lat: 30.7333, lng: 76.7794, costIndex: 2, popularity: 3, highlights: ["Rock Garden", "Sukhna Lake"] },
  { name: "Mysore", country: "India", region: "Asia", lat: 12.2958, lng: 76.6394, costIndex: 1, popularity: 3, highlights: ["Mysore Palace", "Chamundi Hill"] },
  { name: "Bhopal", country: "India", region: "Asia", lat: 23.2599, lng: 77.4126, costIndex: 1, popularity: 2, highlights: ["Upper Lake", "Sanchi Stupa"] },
  { name: "Indore", country: "India", region: "Asia", lat: 22.7196, lng: 75.8577, costIndex: 1, popularity: 2, highlights: ["Rajwada", "Sarafa Bazar"] },
  { name: "Guwahati", country: "India", region: "Asia", lat: 26.1445, lng: 91.7362, costIndex: 1, popularity: 2, highlights: ["Kamakhya Temple", "Brahmaputra River"] },
  { name: "Patna", country: "India", region: "Asia", lat: 25.5941, lng: 85.1376, costIndex: 1, popularity: 2, highlights: ["Golghar", "Mahavir Mandir"] },
  { name: "Ranchi", country: "India", region: "Asia", lat: 23.3441, lng: 85.3096, costIndex: 1, popularity: 2, highlights: ["Dassam Falls", "Jagannath Temple"] },
  { name: "Raipur", country: "India", region: "Asia", lat: 21.2514, lng: 81.6296, costIndex: 1, popularity: 2, highlights: ["Marine Drive", "Swami Vivekananda Sarovar"] },
  { name: "Bhubaneswar", country: "India", region: "Asia", lat: 20.2961, lng: 85.8245, costIndex: 1, popularity: 2, highlights: ["Lingaraja Temple", "Udayagiri Caves"] },
  { name: "Visakhapatnam", country: "India", region: "Asia", lat: 17.6868, lng: 83.2185, costIndex: 2, popularity: 3, highlights: ["RK Beach", "Kailasagiri"] },
  { name: "Vijayawada", country: "India", region: "Asia", lat: 16.5062, lng: 80.6480, costIndex: 1, popularity: 2, highlights: ["Kanaka Durga Temple", "Undavalli Caves"] },
  { name: "Madurai", country: "India", region: "Asia", lat: 9.9252, lng: 78.1198, costIndex: 1, popularity: 3, highlights: ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace"] },
  { name: "Coimbatore", country: "India", region: "Asia", lat: 11.0168, lng: 76.9558, costIndex: 2, popularity: 2, highlights: ["Marudhamalai Temple", "Adiyogi Shiva"] },
  { name: "Trivandrum", country: "India", region: "Asia", lat: 8.5241, lng: 76.9366, costIndex: 2, popularity: 3, highlights: ["Padmanabhaswamy Temple", "Kovalam Beach"] },
  { name: "Paris", country: "France", region: "Europe", lat: 48.8566, lng: 2.3522, costIndex: 4, popularity: 5, highlights: ["Eiffel Tower", "Louvre"] },
  { name: "Marseille", country: "France", region: "Europe", lat: 43.2965, lng: 5.3698, costIndex: 3, popularity: 4, highlights: ["Vieux-Port", "Notre-Dame de la Garde"] },
  { name: "Lyon", country: "France", region: "Europe", lat: 45.7640, lng: 4.8357, costIndex: 3, popularity: 4, highlights: ["Vieux Lyon", "Basilica of Notre-Dame de Fourvière"] },
  { name: "Toulouse", country: "France", region: "Europe", lat: 43.6047, lng: 1.4442, costIndex: 3, popularity: 3, highlights: ["Place du Capitole", "Basilica of Saint-Sernin"] },
  { name: "Nice", country: "France", region: "Europe", lat: 43.7102, lng: 7.2620, costIndex: 4, popularity: 5, highlights: ["Promenade des Anglais", "Old Town"] },
  { name: "Nantes", country: "France", region: "Europe", lat: 47.2184, lng: -1.5536, costIndex: 3, popularity: 3, highlights: ["Château des ducs de Bretagne", "Machines de l'île"] },
  { name: "Strasbourg", country: "France", region: "Europe", lat: 48.5734, lng: 7.7521, costIndex: 3, popularity: 4, highlights: ["Strasbourg Cathedral", "La Petite France"] },
  { name: "Montpellier", country: "France", region: "Europe", lat: 43.6108, lng: 3.8767, costIndex: 3, popularity: 3, highlights: ["Place de la Comédie", "Montpellier Cathedral"] },
  { name: "Bordeaux", country: "France", region: "Europe", lat: 44.8378, lng: -0.5792, costIndex: 4, popularity: 4, highlights: ["Place de la Bourse", "Wine Tasting"] },
  { name: "Lille", country: "France", region: "Europe", lat: 50.6292, lng: 3.0573, costIndex: 3, popularity: 3, highlights: ["Grand Place", "Palais des Beaux-Arts"] },
  { name: "Rome", country: "Italy", region: "Europe", lat: 41.9028, lng: 12.4964, costIndex: 3, popularity: 5, highlights: ["Colosseum", "Trevi Fountain"] },
  { name: "Milan", country: "Italy", region: "Europe", lat: 45.4642, lng: 9.1899, costIndex: 5, popularity: 5, highlights: ["Duomo di Milano", "Galleria Vittorio Emanuele II"] },
  { name: "Naples", country: "Italy", region: "Europe", lat: 40.8518, lng: 14.2681, costIndex: 2, popularity: 4, highlights: ["Pompeii", "Pizza Napoletana"] },
  { name: "Turin", country: "Italy", region: "Europe", lat: 45.0703, lng: 7.6869, costIndex: 3, popularity: 3, highlights: ["Mole Antonelliana", "Egyptian Museum"] },
  { name: "Palermo", country: "Italy", region: "Europe", lat: 38.1157, lng: 13.3615, costIndex: 2, popularity: 4, highlights: ["Palermo Cathedral", "Teatro Massimo"] },
  { name: "Genoa", country: "Italy", region: "Europe", lat: 44.4056, lng: 8.9463, costIndex: 3, popularity: 3, highlights: ["Aquarium of Genoa", "Palazzi dei Rolli"] },
  { name: "Bologna", country: "Italy", region: "Europe", lat: 44.4949, lng: 11.3426, costIndex: 3, popularity: 4, highlights: ["Two Towers", "Piazza Maggiore"] },
  { name: "Florence", country: "Italy", region: "Europe", lat: 43.7696, lng: 11.2558, costIndex: 4, popularity: 5, highlights: ["Florence Cathedral", "Uffizi Gallery"] },
  { name: "Bari", country: "Italy", region: "Europe", lat: 41.1171, lng: 16.8719, costIndex: 2, popularity: 3, highlights: ["Basilica di San Nicola", "Old Town"] },
  { name: "Catania", country: "Italy", region: "Europe", lat: 37.5079, lng: 15.0830, costIndex: 2, popularity: 3, highlights: ["Mount Etna", "Catania Cathedral"] },
  { name: "Venice", country: "Italy", region: "Europe", lat: 45.4408, lng: 12.3155, costIndex: 5, popularity: 5, highlights: ["St. Mark's Basilica", "Grand Canal"] },
  { name: "Madrid", country: "Spain", region: "Europe", lat: 40.4168, lng: -3.7038, costIndex: 3, popularity: 5, highlights: ["Royal Palace", "Prado Museum"] },
  { name: "Barcelona", country: "Spain", region: "Europe", lat: 41.3851, lng: 2.1734, costIndex: 4, popularity: 5, highlights: ["Sagrada Familia", "Park Güell"] },
  { name: "Valencia", country: "Spain", region: "Europe", lat: 39.4699, lng: -0.3763, costIndex: 3, popularity: 4, highlights: ["City of Arts and Sciences", "Valencia Cathedral"] },
  { name: "Seville", country: "Spain", region: "Europe", lat: 37.3891, lng: -5.9845, costIndex: 3, popularity: 5, highlights: ["Alcázar of Seville", "Seville Cathedral"] },
  { name: "Zaragoza", country: "Spain", region: "Europe", lat: 41.6488, lng: -0.8891, costIndex: 2, popularity: 3, highlights: ["Basilica of Our Lady of the Pillar", "Aljafería Palace"] },
  { name: "Málaga", country: "Spain", region: "Europe", lat: 36.7213, lng: -4.4214, costIndex: 3, popularity: 5, highlights: ["Alcazaba", "Picasso Museum"] },
  { name: "Murcia", country: "Spain", region: "Europe", lat: 37.9922, lng: -1.1307, costIndex: 2, popularity: 2, highlights: ["Murcia Cathedral", "Real Casino de Murcia"] },
  { name: "Palma", country: "Spain", region: "Europe", lat: 39.5696, lng: 2.6502, costIndex: 4, popularity: 5, highlights: ["Palma Cathedral", "Bellver Castle"] },
  { name: "Las Palmas", country: "Spain", region: "Europe", lat: 28.1235, lng: -15.4363, costIndex: 3, popularity: 4, highlights: ["Las Canteras Beach", "Vegueta"] },
  { name: "Bilbao", country: "Spain", region: "Europe", lat: 43.2630, lng: -2.9350, costIndex: 3, popularity: 4, highlights: ["Guggenheim Museum", "Casco Viejo"] },
  { name: "Alicante", country: "Spain", region: "Europe", lat: 38.3452, lng: -0.4810, costIndex: 3, popularity: 4, highlights: ["Santa Bárbara Castle", "Explanada de España"] },
  { name: "Cordoba", country: "Spain", region: "Europe", lat: 37.8882, lng: -4.7794, costIndex: 3, popularity: 4, highlights: ["Mosque-Cathedral", "Roman Bridge"] },
  { name: "Granada", country: "Spain", region: "Europe", lat: 37.1773, lng: -3.5986, costIndex: 3, popularity: 5, highlights: ["Alhambra", "Generalife"] },
  { name: "Lisbon", country: "Portugal", region: "Europe", lat: 38.7223, lng: -9.1393, costIndex: 3, popularity: 5, highlights: ["Belem Tower", "Alfama"] },
  { name: "Porto", country: "Portugal", region: "Europe", lat: 41.1579, lng: -8.6291, costIndex: 3, popularity: 5, highlights: ["Ribeira", "Dom Luís I Bridge"] },
  { name: "Vienna", country: "Austria", region: "Europe", lat: 48.2082, lng: 16.3738, costIndex: 4, popularity: 5, highlights: ["Schönbrunn Palace", "St. Stephen's Cathedral"] },
  { name: "Prague", country: "Czech Republic", region: "Europe", lat: 50.0755, lng: 14.4378, costIndex: 2, popularity: 5, highlights: ["Charles Bridge", "Prague Castle"] },
  { name: "Budapest", country: "Hungary", region: "Europe", lat: 47.4979, lng: 19.0402, costIndex: 2, popularity: 5, highlights: ["Parliament Building", "Buda Castle"] },
  { name: "Warsaw", country: "Poland", region: "Europe", lat: 52.2297, lng: 21.0122, costIndex: 2, popularity: 4, highlights: ["Old Town", "Royal Castle"] },
  { name: "Athens", country: "Greece", region: "Europe", lat: 37.9838, lng: 23.7275, costIndex: 3, popularity: 5, highlights: ["Acropolis", "Parthenon"] },
  { name: "Stockholm", country: "Sweden", region: "Europe", lat: 59.3293, lng: 18.0686, costIndex: 5, popularity: 5, highlights: ["Vasa Museum", "Gamla Stan"] },
  { name: "Oslo", country: "Norway", region: "Europe", lat: 59.9139, lng: 10.7522, costIndex: 5, popularity: 5, highlights: ["Vigeland Park", "Operahuset"] },
  { name: "Copenhagen", country: "Denmark", region: "Europe", lat: 55.6761, lng: 12.5683, costIndex: 5, popularity: 5, highlights: ["Nyhavn", "The Little Mermaid"] },
  { name: "Helsinki", country: "Finland", region: "Europe", lat: 60.1699, lng: 24.9384, costIndex: 5, popularity: 5, highlights: ["Helsinki Cathedral", "Suomenlinna"] },
  { name: "Moscow", country: "Russia", region: "Europe", lat: 55.7558, lng: 37.6173, costIndex: 3, popularity: 5, highlights: ["Red Square", "Kremlin"] },
  { name: "Toronto", country: "Canada", region: "Americas", lat: 43.6532, lng: -79.3832, costIndex: 4, popularity: 5, highlights: ["CN Tower", "Distillery District"] },
  { name: "Vancouver", country: "Canada", region: "Americas", lat: 49.2827, lng: -123.1207, costIndex: 5, popularity: 5, highlights: ["Stanley Park", "Granville Island"] },
  { name: "Mexico City", country: "Mexico", region: "Americas", lat: 19.4326, lng: -99.1332, costIndex: 2, popularity: 5, highlights: ["Zócalo", "Teotihuacan"] },
  { name: "Buenos Aires", country: "Argentina", region: "Americas", lat: -34.6037, lng: -58.3816, costIndex: 2, popularity: 5, highlights: ["Teatro Colón", "La Boca"] },
  { name: "Santiago", country: "Chile", region: "Americas", lat: -33.4489, lng: -70.6693, costIndex: 3, popularity: 4, highlights: ["Costanera Center", "Plaza de Armas"] },
  { name: "Lima", country: "Peru", region: "Americas", lat: -12.0464, lng: -77.0428, costIndex: 2, popularity: 5, highlights: ["Plaza Mayor", "Miraflores"] },
  { name: "Bogota", country: "Colombia", region: "Americas", lat: 4.7110, lng: -74.0721, costIndex: 2, popularity: 4, highlights: ["Monserrate", "Gold Museum"] },
  { name: "Casablanca", country: "Morocco", region: "Africa", lat: 33.5731, lng: -7.5898, costIndex: 2, popularity: 4, highlights: ["Hassan II Mosque", "Old Medina"] },
  { name: "Nairobi", country: "Kenya", region: "Africa", lat: -1.2921, lng: 36.8219, costIndex: 2, popularity: 3, highlights: ["Nairobi National Park", "David Sheldrick Wildlife Trust"] },
  { name: "Lagos", country: "Nigeria", region: "Africa", lat: 6.5244, lng: 3.3792, costIndex: 2, popularity: 3, highlights: ["Nike Art Gallery", "Lekki Conservation Centre"] },
  { name: "Marrakech", country: "Morocco", region: "Africa", lat: 31.6295, lng: -7.9811, costIndex: 2, popularity: 5, highlights: ["Jemaa el-Fnaa", "Majorelle Garden"] },
  { name: "Kyoto", country: "Japan", region: "Asia", lat: 35.0116, lng: 135.7681, costIndex: 4, popularity: 5, highlights: ["Fushimi Inari-taisha", "Kinkaku-ji"] },
  { name: "Osaka", country: "Japan", region: "Asia", lat: 34.6937, lng: 135.5023, costIndex: 4, popularity: 5, highlights: ["Osaka Castle", "Dotonbori"] },
  { name: "Beijing", country: "China", region: "Asia", lat: 39.9042, lng: 116.4074, costIndex: 3, popularity: 5, highlights: ["Great Wall of China", "Forbidden City"] },
  { name: "Shanghai", country: "China", region: "Asia", lat: 31.2304, lng: 121.4737, costIndex: 4, popularity: 5, highlights: ["The Bund", "Yu Garden"] },
  { name: "Hong Kong", country: "China", region: "Asia", lat: 22.3193, lng: 114.1694, costIndex: 5, popularity: 5, highlights: ["Victoria Peak", "Star Ferry"] },
  { name: "Taipei", country: "Taiwan", region: "Asia", lat: 25.0330, lng: 121.5654, costIndex: 3, popularity: 5, highlights: ["Taipei 101", "Shilin Night Market"] },
  { name: "Manila", country: "Philippines", region: "Asia", lat: 14.5995, lng: 120.9842, costIndex: 2, popularity: 4, highlights: ["Intramuros", "Rizal Park"] },
  { name: "Ho Chi Minh City", country: "Vietnam", region: "Asia", lat: 10.8231, lng: 106.6297, costIndex: 1, popularity: 5, highlights: ["War Remnants Museum", "Ben Thanh Market"] },
  { name: "Hanoi", country: "Vietnam", region: "Asia", lat: 21.0285, lng: 105.8542, costIndex: 1, popularity: 5, highlights: ["Old Quarter", "Ho Chi Minh Mausoleum"] },
  { name: "Kuala Lumpur", country: "Malaysia", region: "Asia", lat: 3.1390, lng: 101.6869, costIndex: 3, popularity: 5, highlights: ["Petronas Towers", "Batu Caves"] },
  { name: "Jakarta", country: "Indonesia", region: "Asia", lat: -6.2088, lng: 106.8456, costIndex: 2, popularity: 4, highlights: ["Monas", "Ancol Dreamland"] },
  { name: "Bali", country: "Indonesia", region: "Asia", lat: -8.4095, lng: 115.1889, costIndex: 3, popularity: 5, highlights: ["Uluwatu Temple", "Tegallalang Rice Terrace"] },
];
